version: "3.8"

services:
  traffic_simulator:
    build: .
    container_name: traffic_simulator
    environment:
      - DISPLAY=${DISPLAY}
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:ro
    network_mode: "host"  # ✅ Only works on Linux
    stdin_open: true
    tty: true
    working_dir: /app
    command: ["python", "main.py"]
