version: "3.8"

services:
  traffic_simulator:
    build: .
    container_name: traffic_simulator
    environment:
      - DISPLAY=${DISPLAY}
      - SDL_VIDEODRIVER=x11
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/tmp/.docker.xauth:ro
    network_mode: "host"
    stdin_open: true
    tty: true
    command: ["python3", "Traffic Simulator.py"]

